// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTI1yvypKj9i9yupZJxWu6t_5gernXW1c',
    appId: '1:1030980374727:web:006a54edf9dff1dd02eee2',
    messagingSenderId: '1030980374727',
    projectId: 'mini-games-29ed1',
    authDomain: 'mini-games-29ed1.firebaseapp.com',
    storageBucket: 'mini-games-29ed1.firebasestorage.app',
    measurementId: 'G-7PVY35EBNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOX8M7TsOVbJfmbiHqCliJ_MtYZMqY02o',
    appId: '1:1030980374727:android:214aa45757ebb3fb02eee2',
    messagingSenderId: '1030980374727',
    projectId: 'mini-games-29ed1',
    storageBucket: 'mini-games-29ed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjU9CfAj98BwRLSk4DFyxn2Cv9kaZpFzQ',
    appId: '1:1030980374727:ios:e0d29bafde8b1bc902eee2',
    messagingSenderId: '1030980374727',
    projectId: 'mini-games-29ed1',
    storageBucket: 'mini-games-29ed1.firebasestorage.app',
    iosBundleId: 'com.example.miniGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjU9CfAj98BwRLSk4DFyxn2Cv9kaZpFzQ',
    appId: '1:1030980374727:ios:e0d29bafde8b1bc902eee2',
    messagingSenderId: '1030980374727',
    projectId: 'mini-games-29ed1',
    storageBucket: 'mini-games-29ed1.firebasestorage.app',
    iosBundleId: 'com.example.miniGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTI1yvypKj9i9yupZJxWu6t_5gernXW1c',
    appId: '1:1030980374727:web:9e384662e1b5787c02eee2',
    messagingSenderId: '1030980374727',
    projectId: 'mini-games-29ed1',
    authDomain: 'mini-games-29ed1.firebaseapp.com',
    storageBucket: 'mini-games-29ed1.firebasestorage.app',
    measurementId: 'G-0FT0W65YGX',
  );
}
